### ISSUE TITLE
Property Rearranging

### ISSUE THREAD

**Issue by leviFrosty** [while1618/i18n-auto-translation#37]
Thanks so much for your time creating this tool, it's been very helpful to me and my side-project and I appreciate the effort you've put.

I just wanted to ask if you have any suggestions on my issue:

## Issue
I'm currently fighting with property rearranging between `i18-auto-translation` and Crowdin. When running i18-auto-translation, it wants to reorder the properties within objects or nested objects from what it was, based on the name of the property.

## Steps to reproduce:
- Create new `en.json` changes, `i18-auto-translation` does its thing and spits our the machine translations. (Great!)
- Allow Crowdin to sync
- Merge `l10n_development` branch  & resolve merge conflicts because Crowdin reorders properties
- Run `i18-auto-translation`

**At this point the diff to development is just reordering the properties with no actual translations added / changed.**

<img width="1022" alt="image" src="https://github.com/while1618/i18n-auto-translation/assets/79994715/0c32f4e6-044b-429e-92c6-3d2e679efce9">

## Expected behavior
- Create new `en.json` changes, `i18-auto-translation` does its thing and spits our the machine translations. (Great!)
- Allow Crowdin to sync
- Merge `l10n_development` branch  & resolve merge conflicts because Crowdin reorders properties (
- Run `i18-auto-translation`

**At this point the diff to development should be nothing.**

## Comments

I'd say that the default behavior is probably fine for almost everyone, but if you have any suggestions on how I can prevent this it would be great. It's a very large time sync to deal with this sometimes multi-hundred line merge conflicts.

Possible thought on this would be adding some optional flag to the cli params like: `-keepPropertyOrder` or something, but let me know what you think.

Thanks again,
Levi

**Comment by while1618** [comment]
Hi @leviFrosty, sorry for the late response, didn't have access to my pc for some time.

I didn't know that this problem exists, because when you are using string as a key, it won't reorder anything, it just reorders when you use a number.

I think that this doesn't require any flag, it should be default behavior, reordering doesn't seem right.

Will try to fix this, and I'll let you know once it's done. Hopefully, it won't be too tricky.

**Comment by leviFrosty** [comment]
@while1618 If you're unable to work on it or can't come up with anything, let me know and I'll take a look to see if I can help and make a PR.

Thanks again!

**Comment by leviFrosty** [comment]
@while1618 

Here's the problem replicated:

<img width="516" alt="image" src="https://github.com/while1618/i18n-auto-translation/assets/79994715/d3667965-9fcd-45ce-9fe3-660bb5171aa2">

Looks like it's related to this [method](https://github.com/while1618/i18n-auto-translation/blob/c2a432f12f5cbbd7e54934bd6495ee6bd2fec8d0/src/translate/translate.ts#L199)

**Comment by while1618** [comment]
It's not. It is related to `JSON.parse()` method.

[StackOverflow](https://stackoverflow.com/a/32006342/13167522).

Is there a way for you to change the structure of your `en.json`?

**Comment by while1618** [comment]
Reorder of entries will occur [here](https://github.com/while1618/i18n-auto-translation/blob/c2a432f12f5cbbd7e54934bd6495ee6bd2fec8d0/src/translate/translate.ts#L40), and I'm not sure that we can do anything about it because objects are not ordered in js. Maybe we can find a way to hack it somehow, but that solution will probably be too ugly. I'll try to find some alternative, but maybe the best why to fix this is to simply change structure of your json file.

**Comment by leviFrosty** [comment]
Hm. I'm trying to think about what we can do here.

Other languages might be able to be used to achieve the functionality... I just can't believe there is no way of doing this in JS to JSON:
<img width="289" alt="image" src="https://github.com/while1618/i18n-auto-translation/assets/79994715/18c48c0b-99b7-45ea-9ed0-e5e5aa419924">

**Comment by while1618** [comment]
It's just js thing. 

`The iteration order for objects follows a certain set of rules since ES2015, but it does not (always) follow the insertion order.`

[StackOverflow](https://stackoverflow.com/a/5525820/13167522)

The only other thing I could find is to use `Map` instead of `Object`, because `Map` will keep the order intact. But the problem with that approach is how to map json string to `Map`, without using `JSON.parse()` method, because that will create an object, and it will reorder entries again.

I was able to create json string to `Map` method with regex, but it doesn't work correctly with nested json. If I find another way, I'll let you know.

**Comment by leviFrosty** [comment]
Yeah, I tried the same operations in python and everything worked how we would expect it to.

Unless we created some internal service that called a python function, I'm not sure there is a way to do it in JS either. I tried looking for some options but no dice.

**Comment by while1618** [comment]
I won't complicate things with calling python just for this case. Maybe the best approach for you is either to change json structure if possible, or to create a fork of my repo, and then use python to solve this problem. If you decide to do it that way, let me know if you need any help with my code.

**Comment by leviFrosty** [comment]
I appreciate your time either way, thanks for the help.
